/*
 * This file is generated by jOOQ.
 */
package top.jayczee.codegen.tables.pojos;


import java.time.LocalDateTime;

import top.jayczee.codegen.tables.interfaces.IDeviceInfo;


/**
 * 设备信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceInfo implements IDeviceInfo {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private LocalDateTime createDt;
    private String        ip;
    private String        deviceName;

    public DeviceInfo() {}

    public DeviceInfo(IDeviceInfo value) {
        this.id = value.getId();
        this.createDt = value.getCreateDt();
        this.ip = value.getIp();
        this.deviceName = value.getDeviceName();
    }

    public DeviceInfo(
        Long          id,
        LocalDateTime createDt,
        String        ip,
        String        deviceName
    ) {
        this.id = id;
        this.createDt = createDt;
        this.ip = ip;
        this.deviceName = deviceName;
    }

    /**
     * Getter for <code>graduation.device_info.id</code>. 主键
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>graduation.device_info.id</code>. 主键
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>graduation.device_info.create_dt</code>. 创建日时(系统)
     */
    @Override
    public LocalDateTime getCreateDt() {
        return this.createDt;
    }

    /**
     * Setter for <code>graduation.device_info.create_dt</code>. 创建日时(系统)
     */
    @Override
    public void setCreateDt(LocalDateTime createDt) {
        this.createDt = createDt;
    }

    /**
     * Getter for <code>graduation.device_info.ip</code>. ip地址
     */
    @Override
    public String getIp() {
        return this.ip;
    }

    /**
     * Setter for <code>graduation.device_info.ip</code>. ip地址
     */
    @Override
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * Getter for <code>graduation.device_info.device_name</code>. 设备名称
     */
    @Override
    public String getDeviceName() {
        return this.deviceName;
    }

    /**
     * Setter for <code>graduation.device_info.device_name</code>. 设备名称
     */
    @Override
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DeviceInfo (");

        sb.append(id);
        sb.append(", ").append(createDt);
        sb.append(", ").append(ip);
        sb.append(", ").append(deviceName);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IDeviceInfo from) {
        setId(from.getId());
        setCreateDt(from.getCreateDt());
        setIp(from.getIp());
        setDeviceName(from.getDeviceName());
    }

    @Override
    public <E extends IDeviceInfo> E into(E into) {
        into.from(this);
        return into;
    }
}
