/*
 * This file is generated by jOOQ.
 */
package top.jayczee.codegen.tables.pojos;


import java.time.LocalDateTime;

import top.jayczee.codegen.tables.interfaces.IDeviceConfig;


/**
 * 设备配置表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceConfig implements IDeviceConfig {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private LocalDateTime createDt;
    private Long          deviceId;
    private String        configKey;
    private String        configVal;
    private Boolean       isDelete;

    public DeviceConfig() {}

    public DeviceConfig(IDeviceConfig value) {
        this.id = value.getId();
        this.createDt = value.getCreateDt();
        this.deviceId = value.getDeviceId();
        this.configKey = value.getConfigKey();
        this.configVal = value.getConfigVal();
        this.isDelete = value.getIsDelete();
    }

    public DeviceConfig(
        Long          id,
        LocalDateTime createDt,
        Long          deviceId,
        String        configKey,
        String        configVal,
        Boolean       isDelete
    ) {
        this.id = id;
        this.createDt = createDt;
        this.deviceId = deviceId;
        this.configKey = configKey;
        this.configVal = configVal;
        this.isDelete = isDelete;
    }

    /**
     * Getter for <code>graduation.device_config.id</code>. 主键
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>graduation.device_config.id</code>. 主键
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>graduation.device_config.create_dt</code>. 创建日时(系统)
     */
    @Override
    public LocalDateTime getCreateDt() {
        return this.createDt;
    }

    /**
     * Setter for <code>graduation.device_config.create_dt</code>. 创建日时(系统)
     */
    @Override
    public void setCreateDt(LocalDateTime createDt) {
        this.createDt = createDt;
    }

    /**
     * Getter for <code>graduation.device_config.device_id</code>. 设备ID
     */
    @Override
    public Long getDeviceId() {
        return this.deviceId;
    }

    /**
     * Setter for <code>graduation.device_config.device_id</code>. 设备ID
     */
    @Override
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Getter for <code>graduation.device_config.config_key</code>. 配置名称
     */
    @Override
    public String getConfigKey() {
        return this.configKey;
    }

    /**
     * Setter for <code>graduation.device_config.config_key</code>. 配置名称
     */
    @Override
    public void setConfigKey(String configKey) {
        this.configKey = configKey;
    }

    /**
     * Getter for <code>graduation.device_config.config_val</code>. 配置值
     */
    @Override
    public String getConfigVal() {
        return this.configVal;
    }

    /**
     * Setter for <code>graduation.device_config.config_val</code>. 配置值
     */
    @Override
    public void setConfigVal(String configVal) {
        this.configVal = configVal;
    }

    /**
     * Getter for <code>graduation.device_config.is_delete</code>. 是否已删除
     */
    @Override
    public Boolean getIsDelete() {
        return this.isDelete;
    }

    /**
     * Setter for <code>graduation.device_config.is_delete</code>. 是否已删除
     */
    @Override
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DeviceConfig (");

        sb.append(id);
        sb.append(", ").append(createDt);
        sb.append(", ").append(deviceId);
        sb.append(", ").append(configKey);
        sb.append(", ").append(configVal);
        sb.append(", ").append(isDelete);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IDeviceConfig from) {
        setId(from.getId());
        setCreateDt(from.getCreateDt());
        setDeviceId(from.getDeviceId());
        setConfigKey(from.getConfigKey());
        setConfigVal(from.getConfigVal());
        setIsDelete(from.getIsDelete());
    }

    @Override
    public <E extends IDeviceConfig> E into(E into) {
        into.from(this);
        return into;
    }
}
