/*
 * This file is generated by jOOQ.
 */
package top.jayczee.codegen.tables.pojos;


import java.time.LocalDateTime;

import top.jayczee.codegen.tables.interfaces.IUserInfo;


/**
 * 用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfo implements IUserInfo {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private LocalDateTime createDt;
    private String        loginName;
    private String        password;

    public UserInfo() {}

    public UserInfo(IUserInfo value) {
        this.id = value.getId();
        this.createDt = value.getCreateDt();
        this.loginName = value.getLoginName();
        this.password = value.getPassword();
    }

    public UserInfo(
        Long          id,
        LocalDateTime createDt,
        String        loginName,
        String        password
    ) {
        this.id = id;
        this.createDt = createDt;
        this.loginName = loginName;
        this.password = password;
    }

    /**
     * Getter for <code>graduation.user_info.id</code>. 主键
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>graduation.user_info.id</code>. 主键
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>graduation.user_info.create_dt</code>. 创建日时(系统)
     */
    @Override
    public LocalDateTime getCreateDt() {
        return this.createDt;
    }

    /**
     * Setter for <code>graduation.user_info.create_dt</code>. 创建日时(系统)
     */
    @Override
    public void setCreateDt(LocalDateTime createDt) {
        this.createDt = createDt;
    }

    /**
     * Getter for <code>graduation.user_info.login_name</code>. 账号
     */
    @Override
    public String getLoginName() {
        return this.loginName;
    }

    /**
     * Setter for <code>graduation.user_info.login_name</code>. 账号
     */
    @Override
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * Getter for <code>graduation.user_info.password</code>. 密码
     */
    @Override
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>graduation.user_info.password</code>. 密码
     */
    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserInfo (");

        sb.append(id);
        sb.append(", ").append(createDt);
        sb.append(", ").append(loginName);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserInfo from) {
        setId(from.getId());
        setCreateDt(from.getCreateDt());
        setLoginName(from.getLoginName());
        setPassword(from.getPassword());
    }

    @Override
    public <E extends IUserInfo> E into(E into) {
        into.from(this);
        return into;
    }
}
