/*
 * This file is generated by jOOQ.
 */
package top.jayczee.codegen.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 设备配置表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IDeviceConfig extends Serializable {

    /**
     * Setter for <code>graduation.device_config.id</code>. 主键
     */
    public void setId(Long value);

    /**
     * Getter for <code>graduation.device_config.id</code>. 主键
     */
    public Long getId();

    /**
     * Setter for <code>graduation.device_config.create_dt</code>. 创建日时(系统)
     */
    public void setCreateDt(LocalDateTime value);

    /**
     * Getter for <code>graduation.device_config.create_dt</code>. 创建日时(系统)
     */
    public LocalDateTime getCreateDt();

    /**
     * Setter for <code>graduation.device_config.device_id</code>. 设备ID
     */
    public void setDeviceId(Long value);

    /**
     * Getter for <code>graduation.device_config.device_id</code>. 设备ID
     */
    public Long getDeviceId();

    /**
     * Setter for <code>graduation.device_config.config_key</code>. 配置名称
     */
    public void setConfigKey(String value);

    /**
     * Getter for <code>graduation.device_config.config_key</code>. 配置名称
     */
    public String getConfigKey();

    /**
     * Setter for <code>graduation.device_config.config_val</code>. 配置值
     */
    public void setConfigVal(String value);

    /**
     * Getter for <code>graduation.device_config.config_val</code>. 配置值
     */
    public String getConfigVal();

    /**
     * Setter for <code>graduation.device_config.is_delete</code>. 是否已删除
     */
    public void setIsDelete(Boolean value);

    /**
     * Getter for <code>graduation.device_config.is_delete</code>. 是否已删除
     */
    public Boolean getIsDelete();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IDeviceConfig
     */
    public void from(IDeviceConfig from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IDeviceConfig
     */
    public <E extends IDeviceConfig> E into(E into);
}
