/*
 * This file is generated by jOOQ.
 */
package top.jayczee.codegen.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 数据记录
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IDeviceData extends Serializable {

    /**
     * Setter for <code>graduation.device_data.id</code>. 主键
     */
    public void setId(Long value);

    /**
     * Getter for <code>graduation.device_data.id</code>. 主键
     */
    public Long getId();

    /**
     * Setter for <code>graduation.device_data.create_dt</code>. 创建日时(系统)
     */
    public void setCreateDt(LocalDateTime value);

    /**
     * Getter for <code>graduation.device_data.create_dt</code>. 创建日时(系统)
     */
    public LocalDateTime getCreateDt();

    /**
     * Setter for <code>graduation.device_data.ip</code>. ip地址
     */
    public void setIp(String value);

    /**
     * Getter for <code>graduation.device_data.ip</code>. ip地址
     */
    public String getIp();

    /**
     * Setter for <code>graduation.device_data.device_id</code>. 设备ID
     */
    public void setDeviceId(Long value);

    /**
     * Getter for <code>graduation.device_data.device_id</code>. 设备ID
     */
    public Long getDeviceId();

    /**
     * Setter for <code>graduation.device_data.data</code>. 数据值
     */
    public void setData(String value);

    /**
     * Getter for <code>graduation.device_data.data</code>. 数据值
     */
    public String getData();

    /**
     * Setter for <code>graduation.device_data.data_type</code>. 数据类型
     */
    public void setDataType(String value);

    /**
     * Getter for <code>graduation.device_data.data_type</code>. 数据类型
     */
    public String getDataType();

    /**
     * Setter for <code>graduation.device_data.is_error</code>. 是否异常
     */
    public void setIsError(Boolean value);

    /**
     * Getter for <code>graduation.device_data.is_error</code>. 是否异常
     */
    public Boolean getIsError();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IDeviceData
     */
    public void from(IDeviceData from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IDeviceData
     */
    public <E extends IDeviceData> E into(E into);
}
