/*
 * This file is generated by jOOQ.
 */
package top.jayczee.codegen.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserInfo extends Serializable {

    /**
     * Setter for <code>graduation.user_info.id</code>. 主键
     */
    public void setId(Long value);

    /**
     * Getter for <code>graduation.user_info.id</code>. 主键
     */
    public Long getId();

    /**
     * Setter for <code>graduation.user_info.create_dt</code>. 创建日时(系统)
     */
    public void setCreateDt(LocalDateTime value);

    /**
     * Getter for <code>graduation.user_info.create_dt</code>. 创建日时(系统)
     */
    public LocalDateTime getCreateDt();

    /**
     * Setter for <code>graduation.user_info.login_name</code>. 账号
     */
    public void setLoginName(String value);

    /**
     * Getter for <code>graduation.user_info.login_name</code>. 账号
     */
    public String getLoginName();

    /**
     * Setter for <code>graduation.user_info.password</code>. 密码
     */
    public void setPassword(String value);

    /**
     * Getter for <code>graduation.user_info.password</code>. 密码
     */
    public String getPassword();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUserInfo
     */
    public void from(IUserInfo from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUserInfo
     */
    public <E extends IUserInfo> E into(E into);
}
