/*
 * This file is generated by jOOQ.
 */
package top.jayczee.codegen.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import top.jayczee.codegen.Graduation;
import top.jayczee.codegen.Keys;
import top.jayczee.codegen.tables.records.UserInfoRecord;


/**
 * 用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoTable extends TableImpl<UserInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>graduation.user_info</code>
     */
    public static final UserInfoTable USER_INFO = new UserInfoTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserInfoRecord> getRecordType() {
        return UserInfoRecord.class;
    }

    /**
     * The column <code>graduation.user_info.id</code>. 主键
     */
    public final TableField<UserInfoRecord, Long> Id = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "主键");

    /**
     * The column <code>graduation.user_info.create_dt</code>. 创建日时(系统)
     */
    public final TableField<UserInfoRecord, LocalDateTime> CreateDt = createField(DSL.name("create_dt"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(3)", SQLDataType.LOCALDATETIME)), this, "创建日时(系统)");

    /**
     * The column <code>graduation.user_info.login_name</code>. 账号
     */
    public final TableField<UserInfoRecord, String> LoginName = createField(DSL.name("login_name"), SQLDataType.VARCHAR(200).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "账号");

    /**
     * The column <code>graduation.user_info.password</code>. 密码
     */
    public final TableField<UserInfoRecord, String> Password = createField(DSL.name("password"), SQLDataType.VARCHAR(200).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "密码");

    /**
     * The column <code>graduation.user_info.salt</code>. 盐
     */
    public final TableField<UserInfoRecord, String> Salt = createField(DSL.name("salt"), SQLDataType.VARCHAR(200).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "盐");

    private UserInfoTable(Name alias, Table<UserInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserInfoTable(Name alias, Table<UserInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("用户信息"), TableOptions.table());
    }

    /**
     * Create an aliased <code>graduation.user_info</code> table reference
     */
    public UserInfoTable(String alias) {
        this(DSL.name(alias), USER_INFO);
    }

    /**
     * Create an aliased <code>graduation.user_info</code> table reference
     */
    public UserInfoTable(Name alias) {
        this(alias, USER_INFO);
    }

    /**
     * Create a <code>graduation.user_info</code> table reference
     */
    public UserInfoTable() {
        this(DSL.name("user_info"), null);
    }

    public <O extends Record> UserInfoTable(Table<O> child, ForeignKey<O, UserInfoRecord> key) {
        super(child, key, USER_INFO);
    }

    @Override
    public Schema getSchema() {
        return Graduation.GRADUATION;
    }

    @Override
    public UniqueKey<UserInfoRecord> getPrimaryKey() {
        return Keys.KEY_USER_INFO_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<UserInfoRecord>>asList(Keys.KEY_USER_INFO_PRIMARY);
    }

    @Override
    public UserInfoTable as(String alias) {
        return new UserInfoTable(DSL.name(alias), this);
    }

    @Override
    public UserInfoTable as(Name alias) {
        return new UserInfoTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserInfoTable rename(String name) {
        return new UserInfoTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserInfoTable rename(Name name) {
        return new UserInfoTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, LocalDateTime, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
