/*
 * This file is generated by jOOQ.
 */
package top.jayczee.codegen;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import top.jayczee.codegen.tables.DeviceConfigTable;
import top.jayczee.codegen.tables.DeviceDataTable;
import top.jayczee.codegen.tables.DeviceInfoTable;
import top.jayczee.codegen.tables.SensorInfoTable;
import top.jayczee.codegen.tables.UserInfoTable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Graduation extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>graduation</code>
     */
    public static final Graduation GRADUATION = new Graduation();

    /**
     * 设备配置表
     */
    public final DeviceConfigTable DEVICE_CONFIG = DeviceConfigTable.DEVICE_CONFIG;

    /**
     * 数据记录
     */
    public final DeviceDataTable DEVICE_DATA = DeviceDataTable.DEVICE_DATA;

    /**
     * 设备信息
     */
    public final DeviceInfoTable DEVICE_INFO = DeviceInfoTable.DEVICE_INFO;

    /**
     * 传感器信息
     */
    public final SensorInfoTable SENSOR_INFO = SensorInfoTable.SENSOR_INFO;

    /**
     * 用户信息
     */
    public final UserInfoTable USER_INFO = UserInfoTable.USER_INFO;

    /**
     * No further instances allowed
     */
    private Graduation() {
        super("graduation", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            DeviceConfigTable.DEVICE_CONFIG,
            DeviceDataTable.DEVICE_DATA,
            DeviceInfoTable.DEVICE_INFO,
            SensorInfoTable.SENSOR_INFO,
            UserInfoTable.USER_INFO);
    }
}
