/*
 * This file is generated by jOOQ.
 */
package top.jayczee.codegen;


import top.jayczee.codegen.tables.UserInfoTable;


/**
 * Convenience access to all tables in graduation.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户信息
     */
    public static final UserInfoTable USER_INFO = UserInfoTable.USER_INFO;
}
