/*
 * This file is generated by jOOQ.
 */
package top.jayczee.codegen.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import top.jayczee.codegen.tables.DeviceConfigTable;
import top.jayczee.codegen.tables.interfaces.IDeviceConfig;


/**
 * 设备配置表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceConfigRecord extends UpdatableRecordImpl<DeviceConfigRecord> implements Record6<Long, LocalDateTime, Long, String, String, Boolean>, IDeviceConfig {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>graduation.device_config.id</code>. 主键
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>graduation.device_config.id</code>. 主键
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>graduation.device_config.create_dt</code>. 创建日时(系统)
     */
    @Override
    public void setCreateDt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>graduation.device_config.create_dt</code>. 创建日时(系统)
     */
    @Override
    public LocalDateTime getCreateDt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>graduation.device_config.device_id</code>. 设备ID
     */
    @Override
    public void setDeviceId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>graduation.device_config.device_id</code>. 设备ID
     */
    @Override
    public Long getDeviceId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>graduation.device_config.config_key</code>. 配置名称
     */
    @Override
    public void setConfigKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>graduation.device_config.config_key</code>. 配置名称
     */
    @Override
    public String getConfigKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>graduation.device_config.config_val</code>. 配置值
     */
    @Override
    public void setConfigVal(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>graduation.device_config.config_val</code>. 配置值
     */
    @Override
    public String getConfigVal() {
        return (String) get(4);
    }

    /**
     * Setter for <code>graduation.device_config.is_delete</code>. 是否已删除
     */
    @Override
    public void setIsDelete(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>graduation.device_config.is_delete</code>. 是否已删除
     */
    @Override
    public Boolean getIsDelete() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, LocalDateTime, Long, String, String, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, LocalDateTime, Long, String, String, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DeviceConfigTable.DEVICE_CONFIG.Id;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return DeviceConfigTable.DEVICE_CONFIG.CreateDt;
    }

    @Override
    public Field<Long> field3() {
        return DeviceConfigTable.DEVICE_CONFIG.DeviceId;
    }

    @Override
    public Field<String> field4() {
        return DeviceConfigTable.DEVICE_CONFIG.ConfigKey;
    }

    @Override
    public Field<String> field5() {
        return DeviceConfigTable.DEVICE_CONFIG.ConfigVal;
    }

    @Override
    public Field<Boolean> field6() {
        return DeviceConfigTable.DEVICE_CONFIG.IsDelete;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDt();
    }

    @Override
    public Long component3() {
        return getDeviceId();
    }

    @Override
    public String component4() {
        return getConfigKey();
    }

    @Override
    public String component5() {
        return getConfigVal();
    }

    @Override
    public Boolean component6() {
        return getIsDelete();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDt();
    }

    @Override
    public Long value3() {
        return getDeviceId();
    }

    @Override
    public String value4() {
        return getConfigKey();
    }

    @Override
    public String value5() {
        return getConfigVal();
    }

    @Override
    public Boolean value6() {
        return getIsDelete();
    }

    @Override
    public DeviceConfigRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DeviceConfigRecord value2(LocalDateTime value) {
        setCreateDt(value);
        return this;
    }

    @Override
    public DeviceConfigRecord value3(Long value) {
        setDeviceId(value);
        return this;
    }

    @Override
    public DeviceConfigRecord value4(String value) {
        setConfigKey(value);
        return this;
    }

    @Override
    public DeviceConfigRecord value5(String value) {
        setConfigVal(value);
        return this;
    }

    @Override
    public DeviceConfigRecord value6(Boolean value) {
        setIsDelete(value);
        return this;
    }

    @Override
    public DeviceConfigRecord values(Long value1, LocalDateTime value2, Long value3, String value4, String value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IDeviceConfig from) {
        setId(from.getId());
        setCreateDt(from.getCreateDt());
        setDeviceId(from.getDeviceId());
        setConfigKey(from.getConfigKey());
        setConfigVal(from.getConfigVal());
        setIsDelete(from.getIsDelete());
    }

    @Override
    public <E extends IDeviceConfig> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeviceConfigRecord
     */
    public DeviceConfigRecord() {
        super(DeviceConfigTable.DEVICE_CONFIG);
    }

    /**
     * Create a detached, initialised DeviceConfigRecord
     */
    public DeviceConfigRecord(Long id, LocalDateTime createDt, Long deviceId, String configKey, String configVal, Boolean isDelete) {
        super(DeviceConfigTable.DEVICE_CONFIG);

        setId(id);
        setCreateDt(createDt);
        setDeviceId(deviceId);
        setConfigKey(configKey);
        setConfigVal(configVal);
        setIsDelete(isDelete);
    }
}
