/*
 * This file is generated by jOOQ.
 */
package top.jayczee.codegen.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import top.jayczee.codegen.tables.SensorInfoTable;
import top.jayczee.codegen.tables.interfaces.ISensorInfo;


/**
 * 传感器信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SensorInfoRecord extends UpdatableRecordImpl<SensorInfoRecord> implements Record5<Long, LocalDateTime, String, Long, Boolean>, ISensorInfo {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>graduation.sensor_info.id</code>. 主键
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>graduation.sensor_info.id</code>. 主键
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>graduation.sensor_info.create_dt</code>. 创建日时(系统)
     */
    @Override
    public void setCreateDt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>graduation.sensor_info.create_dt</code>. 创建日时(系统)
     */
    @Override
    public LocalDateTime getCreateDt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>graduation.sensor_info.sensor_name</code>. 传感器名称
     */
    @Override
    public void setSensorName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>graduation.sensor_info.sensor_name</code>. 传感器名称
     */
    @Override
    public String getSensorName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>graduation.sensor_info.device_id</code>. 设备ID
     */
    @Override
    public void setDeviceId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>graduation.sensor_info.device_id</code>. 设备ID
     */
    @Override
    public Long getDeviceId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>graduation.sensor_info.is_running</code>. 是否打开
     */
    @Override
    public void setIsRunning(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>graduation.sensor_info.is_running</code>. 是否打开
     */
    @Override
    public Boolean getIsRunning() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, LocalDateTime, String, Long, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, LocalDateTime, String, Long, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SensorInfoTable.SENSOR_INFO.Id;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SensorInfoTable.SENSOR_INFO.CreateDt;
    }

    @Override
    public Field<String> field3() {
        return SensorInfoTable.SENSOR_INFO.SensorName;
    }

    @Override
    public Field<Long> field4() {
        return SensorInfoTable.SENSOR_INFO.DeviceId;
    }

    @Override
    public Field<Boolean> field5() {
        return SensorInfoTable.SENSOR_INFO.IsRunning;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDt();
    }

    @Override
    public String component3() {
        return getSensorName();
    }

    @Override
    public Long component4() {
        return getDeviceId();
    }

    @Override
    public Boolean component5() {
        return getIsRunning();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDt();
    }

    @Override
    public String value3() {
        return getSensorName();
    }

    @Override
    public Long value4() {
        return getDeviceId();
    }

    @Override
    public Boolean value5() {
        return getIsRunning();
    }

    @Override
    public SensorInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SensorInfoRecord value2(LocalDateTime value) {
        setCreateDt(value);
        return this;
    }

    @Override
    public SensorInfoRecord value3(String value) {
        setSensorName(value);
        return this;
    }

    @Override
    public SensorInfoRecord value4(Long value) {
        setDeviceId(value);
        return this;
    }

    @Override
    public SensorInfoRecord value5(Boolean value) {
        setIsRunning(value);
        return this;
    }

    @Override
    public SensorInfoRecord values(Long value1, LocalDateTime value2, String value3, Long value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISensorInfo from) {
        setId(from.getId());
        setCreateDt(from.getCreateDt());
        setSensorName(from.getSensorName());
        setDeviceId(from.getDeviceId());
        setIsRunning(from.getIsRunning());
    }

    @Override
    public <E extends ISensorInfo> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SensorInfoRecord
     */
    public SensorInfoRecord() {
        super(SensorInfoTable.SENSOR_INFO);
    }

    /**
     * Create a detached, initialised SensorInfoRecord
     */
    public SensorInfoRecord(Long id, LocalDateTime createDt, String sensorName, Long deviceId, Boolean isRunning) {
        super(SensorInfoTable.SENSOR_INFO);

        setId(id);
        setCreateDt(createDt);
        setSensorName(sensorName);
        setDeviceId(deviceId);
        setIsRunning(isRunning);
    }
}
